"""
Django settings for lost_and_found project.

Generated by 'django-admin startproject' using Django 3.1.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5v(0sdjcz*rm=*t((!yk#+-hl87tuork&!_j4cc7f5*e*a(l!1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'items',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lost_and_found.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lost_and_found.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# MongoDB configuration using djongo
import os

# MongoDB connection settings - you can switch between local and cloud
MONGODB_TYPE = os.getenv('MONGODB_TYPE', 'local')  # 'local' or 'atlas'

if MONGODB_TYPE == 'atlas':
    # ATLAS MongoDB (Cloud Database)
    MONGODB_CONNECTION_STRING = os.getenv('MONGODB_CONNECTION_STRING',
        'mongodb+srv://<username>:<password>@<cluster>.mongodb.net/lost_and_found_db?retryWrites=true&w=majority')

    DATABASES = {
        'default': {
            'ENGINE': 'djongo',
            'NAME': 'lost_and_found_db',
            'ENFORCE_SCHEMA': False,
            'CLIENT': {
                'host': MONGODB_CONNECTION_STRING,
            },
            'LOGGING': {
                'version': 1,
                'loggers': {
                    'djongo': {
                        'level': 'INFO',
                        'propagate': False,
                    }
                },
            },
        }
    }
else:
    # LOCAL MongoDB
    DATABASES = {
        'default': {
            'ENGINE': 'djongo',
            'NAME': 'lost_and_found_db',
            'ENFORCE_SCHEMA': False,
            'CLIENT': {
                'host': 'mongodb://localhost:27017',
                # Remove authentication for local development
                # 'username': '',
                # 'password': '',
                # 'authSource': 'admin',
                # 'authMechanism': 'SCRAM-SHA-1',
            },
            'LOGGING': {
                'version': 1,
                'loggers': {
                    'djongo': {
                        'level': 'INFO',
                        'propagate': False,
                    }
                },
            },
        }
    }

# MongoDB connection settings
MONGODB_SETTINGS = {
    'host': 'mongodb://localhost:27017/lost_and_found_db',
    'connect': False,  # Disable connection pooling for development
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Login URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'
