# Generated by Django 3.1.12 on 2025-06-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20250601_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmatch',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
